<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-MIPU6J0" ignored="0" name="Test" tests="6" failures="2" timestamp="2022-02-13T07:56:31 IST" time="0.337" errors="0">
  <testcase name="ts01" time="0.021" classname="com.jbk.testng.DemoTest"/>
  <testcase name="ts02" time="0.008" classname="com.jbk.testng.DemoTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.jbk.testng.DemoTest.ts02(DemoTest.java:17)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ts02 -->
  <testcase name="ts03" time="0.024" classname="com.jbk.testng.DemoTest">
    <skipped/>
  </testcase> <!-- ts03 -->
  <testcase name="As03" time="0.006" classname="com.jbk.testng.DemoTest2">
    <skipped/>
  </testcase> <!-- As03 -->
  <testcase name="as02" time="0.006" classname="com.jbk.testng.DemoTest2">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.jbk.testng.DemoTest2.as02(DemoTest2.java:17)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- as02 -->
  <testcase name="ts01" time="0.008" classname="com.jbk.testng.DemoTest2"/>
</testsuite> <!-- Test -->
